import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/session-provider";
import NavMenu from "@/components/nav-menu";
import { authOptions } from "@/lib/utils";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavMenu />
          {children}
          <div className="w-full md:h-20 h-12 absolute left-0 bottom-0 md:flex justify-center items-center hidden">
            <p className="text-teal-400 text-base underline">
              Cipher App - Made By @ihbobu
            </p>
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
